apiVersion: v1
kind: Pod
metadata:
  name: beebox-shipping-data
spec:
  containers:
  - image: linuxacademycontent/random-crashing-web-server:1
    imagePullPolicy: IfNotPresent
    name: shipping-data
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
