apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:1.19.1
    name: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: nginxconf
      mountPath: /etc/nginx
    - name: htpasswd
      mountPath: /etc/nginx/conf
  volumes:
  - name: nginxconf
    configMap: 
      name: nginx-config
  - name: htpasswd 
    secret:
      secretName: nginx-htpasswd
